# Generated by Django 4.1.7 on 2023-04-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('data_ref', models.CharField(max_length=200, verbose_name='ruta de archivo')),
                ('check_complete', models.CharField(max_length=200, verbose_name='valor 1 o 0')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rol', models.CharField(max_length=200, verbose_name='nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre de Estudiante')),
                ('last_name', models.CharField(max_length=200, verbose_name='apellido de Estudiante')),
                ('question_u', models.CharField(max_length=200, verbose_name='Pregunta de seguridad')),
                ('response_u', models.CharField(max_length=200, verbose_name='Respuesta correcta')),
                ('students_projects', models.ManyToManyField(to='system.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_u', models.CharField(max_length=200, verbose_name='nombre de usuario')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('roles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.roles')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.projects')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.students')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.users'),
        ),
        migrations.CreateModel(
            name='ProjectsContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.container')),
                ('projects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='projects_students',
            field=models.ManyToManyField(to='system.students'),
        ),
    ]
