# Generated by Django 4.2 on 2023-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_container_options_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name_u',
            field=models.CharField(max_length=200, verbose_name='Nombre de usuario'),
        ),
    ]
