# Generated by Django 4.2 on 2023-05-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_users_email_alter_users_name_u'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relacion Estudiante - Proyecto',
                'verbose_name_plural': 'Relaciones',
            },
        ),
        migrations.RenameModel(
            old_name='ProjectsContainer',
            new_name='ContainerProjects',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projects_students',
        ),
        migrations.RemoveField(
            model_name='students',
            name='students_projects',
        ),
        migrations.AddField(
            model_name='container',
            name='container_projects',
            field=models.ManyToManyField(to='system.projects'),
        ),
        migrations.AddField(
            model_name='container',
            name='container_students',
            field=models.ManyToManyField(to='system.students'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projects_container',
            field=models.ManyToManyField(to='system.container'),
        ),
        migrations.AddField(
            model_name='students',
            name='students_container',
            field=models.ManyToManyField(to='system.container'),
        ),
        migrations.DeleteModel(
            name='StudentsProjects',
        ),
        migrations.AddField(
            model_name='studentscontainer',
            name='container_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.container'),
        ),
        migrations.AddField(
            model_name='studentscontainer',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.students'),
        ),
    ]
